services:
  db:
    image: postgres:15-alpine
    container_name: ringmig_postgres
    environment:
      POSTGRES_DB: ringmig_db
      POSTGRES_USER: ringmig_user
      POSTGRES_PASSWORD: ringmig_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ringmig_user -d ringmig_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ringmig_redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: ringmig_web
    command: bash -c "cd /app/core && python manage.py migrate && python manage.py collectstatic --noinput && exec python -m daphne -b 0.0.0.0 -p 8006 core.asgi:application"
    env_file:
      - .env
    environment:
      DEBUG: "False"
      DB_ENGINE: "django.db.backends.postgresql"
      DB_NAME: "ringmig_db"
      DB_USER: "ringmig_user"
      DB_PASSWORD: "ringmig_password_123"
      DB_HOST: "db"
      DB_PORT: "5432"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    volumes:
      - .:/app
      - media_data:/app/core/media
      - static_data:/app/core/static
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure

  frontend:
    build:
      context: /root/frontend/ring_mig  # <--- Change this line to the exact path
    container_name: ringmig_frontend
    restart: always
    # No ports needed here, Nginx will talk to it internally

  nginx:
    image: nginx:alpine
    container_name: ringmig_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_data:/app/backend_static:ro # To serve Django static files
      - media_data:/app/backend_media:ro   # To serve Django media files
    depends_on:
      - web
      - frontend
    restart: unless-stopped

volumes:
  postgres_data:
  media_data:
  static_data: