server {
    listen 80;
    server_name ring-mig.com www.ring-mig.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name ring-mig.com www.ring-mig.com;

    ssl_certificate /etc/letsencrypt/live/ring-mig.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ring-mig.com/privkey.pem;

    server_tokens off;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    resolver 127.0.0.11 valid=30s;

    location / {
        set $frontend_upstream http://frontend:80;
        proxy_pass $frontend_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name dev.backend.ring-mig.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name dev.backend.ring-mig.com;

    ssl_certificate /etc/letsencrypt/live/dev.backend.ring-mig.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev.backend.ring-mig.com/privkey.pem;

    client_max_body_size 1000M;
    resolver 127.0.0.11 valid=30s;

    # Django Static Files
    location /static/ {
        alias /app/backend_static/;
    }

    # Django Media Files
    location /media/ {
        alias /app/backend_media/;
    }

    location / {
        set $backend_upstream http://web:8006;
        proxy_pass $backend_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
