# Generated by Django 5.2.4 on 2026-01-14 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When listener accepted', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='initial_message',
            field=models.TextField(blank=True, help_text='Initial message from talker'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When listener rejected', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', help_text='Conversation status', max_length=20),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', '-created_at'], name='chat_conver_status_0a9500_idx'),
        ),
    ]
