# Generated by Django 5.2.4 on 2026-01-23 07:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_accepted_at_and_more'),
        ('payment', '0002_alter_payment_stripe_payment_intent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalCallPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Package name', max_length=100)),
                ('package_type', models.CharField(choices=[('audio', 'Audio Call'), ('video', 'Video Call'), ('both', 'Audio/Video Call')], default='audio', help_text='Type of call package', max_length=20)),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('app_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='App commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Package available for purchase')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Universal Call Package',
                'verbose_name_plural': 'Universal Call Packages',
                'ordering': ['duration_minutes', 'price'],
            },
        ),
        migrations.CreateModel(
            name='CallPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('app_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('listener_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listener', models.ForeignKey(limit_choices_to={'user_type': 'listener'}, on_delete=django.db.models.deletion.CASCADE, related_name='listener_call_packages', to=settings.AUTH_USER_MODEL)),
                ('talker', models.ForeignKey(limit_choices_to={'user_type': 'talker'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_call_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Package Purchase',
                'verbose_name_plural': 'Call Package Purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('connecting', 'Connecting'), ('active', 'Active'), ('ended', 'Ended'), ('timeout', 'Timeout'), ('failed', 'Failed')], default='connecting', max_length=20)),
                ('total_minutes_purchased', models.IntegerField(default=0, help_text='Total minutes purchased for this call')),
                ('minutes_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minutes actually used', max_digits=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_warning_sent', models.BooleanField(default=False, help_text='Whether 3-minute warning was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, help_text='Related booking if using booking system', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_session', to='payment.booking')),
                ('call_package', models.OneToOneField(blank=True, help_text='Call package used for this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_call_session', to='chat.callpackage')),
                ('initial_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_sessions', to='chat.callpackage')),
                ('listener', models.ForeignKey(limit_choices_to={'user_type': 'listener'}, on_delete=django.db.models.deletion.CASCADE, related_name='listener_call_sessions', to=settings.AUTH_USER_MODEL)),
                ('talker', models.ForeignKey(limit_choices_to={'user_type': 'talker'}, on_delete=django.db.models.deletion.CASCADE, related_name='talker_call_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Session',
                'verbose_name_plural': 'Call Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='callpackage',
            name='call_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='chat.callsession'),
        ),
        migrations.AddField(
            model_name='callpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_packages', to='chat.universalcallpackage'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['talker', 'status'], name='chat_callse_talker__f1c2af_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['listener', 'status'], name='chat_callse_listene_54fc1c_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['status', 'started_at'], name='chat_callse_status_736685_idx'),
        ),
        migrations.AddIndex(
            model_name='callpackage',
            index=models.Index(fields=['talker', 'status'], name='chat_callpa_talker__cd1a99_idx'),
        ),
        migrations.AddIndex(
            model_name='callpackage',
            index=models.Index(fields=['listener', 'status'], name='chat_callpa_listene_84f3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='callpackage',
            index=models.Index(fields=['status', '-created_at'], name='chat_callpa_status_a6850b_idx'),
        ),
    ]
