# Generated by Django 5.2.4 on 2026-01-24 06:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_universalcallpackage_callpackage_callsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not_available', 'Not Available'), ('busy', 'Busy'), ('not_interested', 'Not Interested'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes')),
                ('refund_issued', models.BooleanField(default=False, help_text='Whether refund was processed')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount refunded to talker', max_digits=10)),
                ('refund_stripe_id', models.CharField(blank=True, help_text='Stripe refund ID', max_length=255)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection', to='chat.callpackage')),
                ('listener', models.ForeignKey(limit_choices_to={'user_type': 'listener'}, on_delete=django.db.models.deletion.CASCADE, related_name='call_rejections', to=settings.AUTH_USER_MODEL)),
                ('talker', models.ForeignKey(limit_choices_to={'user_type': 'talker'}, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Rejection',
                'verbose_name_plural': 'Call Rejections',
                'ordering': ['-rejected_at'],
                'indexes': [models.Index(fields=['listener', 'rejected_at'], name='chat_callre_listene_b9c787_idx'), models.Index(fields=['talker', 'rejected_at'], name='chat_callre_talker__e2b3df_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListenerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid to listener', max_digits=10)),
                ('status', models.CharField(choices=[('earned', 'Earned'), ('pending', 'Pending Payout'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='earned', max_length=20)),
                ('stripe_payout_id', models.CharField(blank=True, help_text='Stripe payout ID', max_length=255)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('payout_requested_at', models.DateTimeField(blank=True, null=True)),
                ('payout_completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='chat.callpackage')),
                ('listener', models.ForeignKey(limit_choices_to={'user_type': 'listener'}, on_delete=django.db.models.deletion.CASCADE, related_name='listener_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listener Payout',
                'verbose_name_plural': 'Listener Payouts',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['listener', 'status'], name='chat_listen_listene_0088d4_idx'), models.Index(fields=['listener', '-earned_at'], name='chat_listen_listene_7d91bb_idx')],
            },
        ),
    ]
