# Generated by Django 5.2.4 on 2026-01-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_callrejection_listenerpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='callpackage',
            name='is_extension',
            field=models.BooleanField(default=False, help_text='Whether this is an extension package for additional minutes'),
        ),
        migrations.AddField(
            model_name='listenerpayout',
            name='is_extension',
            field=models.BooleanField(default=False, help_text='Extension payouts are not counted in total balance'),
        ),
    ]
