# Generated by Django 5.2.4 on 2026-01-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_add_is_extension_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='end_reason',
            field=models.CharField(blank=True, default='', help_text='Reason why call ended', max_length=255),
        ),
        migrations.AddField(
            model_name='callsession',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Alias for ended_at', null=True),
        ),
    ]
