# Generated by Django 5.2.4 on 2026-01-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_callsession_end_reason_callsession_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsession',
            name='end_time',
        ),
    ]
