# Generated by Django 5.2.4 on 2026-01-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_callsession_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='end_reason',
            field=models.CharField(blank=True, default='', help_text='Reason why call ended', max_length=255, null=True),
        ),
    ]
