# Generated by Django 5.2.4 on 2026-01-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_callsession_end_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='callpackage',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='When the package was used/extension was applied', null=True),
        ),
    ]
