# Generated by Django 5.2.4 on 2026-01-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_callpackage_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='agora_channel_name',
            field=models.CharField(blank=True, help_text='Agora channel name for the call', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='agora_listener_token',
            field=models.TextField(blank=True, help_text='Agora RTC token for listener', null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='agora_listener_uid',
            field=models.IntegerField(blank=True, help_text='Agora UID for listener', null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='agora_talker_token',
            field=models.TextField(blank=True, help_text='Agora RTC token for talker', null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='agora_talker_uid',
            field=models.IntegerField(blank=True, help_text='Agora UID for talker', null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='agora_tokens_generated_at',
            field=models.DateTimeField(blank=True, help_text='When Agora tokens were generated', null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='call_type',
            field=models.CharField(choices=[('audio', 'Audio Call'), ('video', 'Video Call')], default='audio', help_text='Type of call based on package', max_length=20),
        ),
    ]
