# Generated by Django 5.2.4 on 2026-04-13 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_callsession_agora_channel_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_refund', 'Booking Refund'), ('booking_deleted', 'Booking Deleted'), ('booking_reminder', 'Booking Reminder'), ('pending_conversation', 'Pending Conversation'), ('message_received', 'Message Received'), ('call_started', 'Call Started'), ('call_ended', 'Call Ended'), ('listener_balance_added', 'Listener Balance Added'), ('talker_payout_created', 'Talker Payout Created'), ('payout_completed', 'Payout Completed'), ('general', 'General Notification')], default='general', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data in JSON format')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='chat_notifi_user_id_067519_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='chat_notifi_user_id_028bb1_idx')],
            },
        ),
    ]
