# Generated by Django 5.2.4 on 2026-05-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_privacy_policy_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Privacy Policy', 'verbose_name_plural': 'Privacy Policy'},
        ),
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'verbose_name': 'Terms and Conditions', 'verbose_name_plural': 'Terms and Conditions'},
        ),
        migrations.AddField(
            model_name='callpackage',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, default='', help_text='Stripe checkout session ID', max_length=255),
        ),
        migrations.AddField(
            model_name='callpackage',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, default='', help_text='Stripe transfer ID to listener account', max_length=255),
        ),
    ]
