# Generated by Django 5.2.4 on 2026-06-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_add_stripe_transfer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_refund', 'Booking Refund'), ('booking_deleted', 'Booking Deleted'), ('booking_reminder', 'Booking Reminder'), ('pending_conversation', 'Pending Conversation'), ('booking_completed', 'Booking Completed'), ('message_received', 'Message Received'), ('call_started', 'Call Started'), ('call_ended', 'Call Ended'), ('listener_balance_added', 'Listener Balance Added'), ('talker_payout_created', 'Talker Payout Created'), ('payout_completed', 'Payout Completed'), ('general', 'General Notification')], default='general', max_length=50),
        ),
    ]
