# Generated by Django 5.2.4 on 2026-01-13 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='talker_profiles/')),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=255)),
                ('about_me', models.TextField(blank=True, help_text='Tell listeners about yourself')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talker Profile',
                'verbose_name_plural': 'Talker Profiles',
            },
        ),
    ]
