# Generated by Django 5.2.4 on 2026-01-31 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0007_listenerbalance'),
        ('talker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteListener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_talkers', to='listener.listenerprofile')),
                ('talker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_listeners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Listener',
                'verbose_name_plural': 'Favorite Listeners',
                'ordering': ['-added_at'],
                'unique_together': {('talker', 'listener')},
            },
        ),
    ]
