# Generated by Django 5.2.4 on 2026-02-08 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talker', '0002_favoritelistener'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkerSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('reports', 'Multiple Reports'), ('violation', 'Account Violation'), ('manual', 'Manual Suspension')], default='reports', max_length=50)),
                ('suspended_at', models.DateTimeField(auto_now_add=True)),
                ('resume_at', models.DateTimeField(help_text='When the suspension will be lifted')),
                ('is_active', models.BooleanField(default=True, help_text='Whether suspension is currently active')),
                ('days_suspended', models.IntegerField(default=7, help_text='Number of days the account is suspended')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about the suspension')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('talker', models.OneToOneField(limit_choices_to={'user_type': 'talker'}, on_delete=django.db.models.deletion.CASCADE, related_name='suspension', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talker Suspension',
                'verbose_name_plural': 'Talker Suspensions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TalkerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('harassment', 'Harassment or Abuse'), ('inappropriate_content', 'Inappropriate Content'), ('scam', 'Scam or Fraud'), ('hate_speech', 'Hate Speech'), ('threatening', 'Threatening Behavior'), ('fake_profile', 'Fake Profile'), ('other', 'Other')], help_text='Reason for reporting', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the issue')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(limit_choices_to={'user_type': 'listener'}, on_delete=django.db.models.deletion.CASCADE, related_name='talker_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talker_reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('talker', models.ForeignKey(limit_choices_to={'user_type': 'talker'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against_talker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talker Report',
                'verbose_name_plural': 'Talker Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['talker', 'status'], name='talker_talk_talker__1788a0_idx'), models.Index(fields=['status', 'created_at'], name='talker_talk_status_90b2b9_idx')],
            },
        ),
    ]
