# Generated by Django 5.2.4 on 2026-03-11 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalComToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Cal.com OAuth2 access token or API key')),
                ('refresh_token', models.TextField(blank=True, default='', help_text='Cal.com OAuth2 refresh token')),
                ('token_type', models.CharField(choices=[('OAuth', 'OAuth2 Token'), ('ApiKey', 'API Key')], default='OAuth', max_length=10)),
                ('cal_user_id', models.CharField(blank=True, default='', help_text='Cal.com user ID', max_length=100)),
                ('scope', models.CharField(blank=True, default='', help_text='Granted OAuth scopes', max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token expiry time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calcom_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cal.com Token',
                'verbose_name_plural': 'Cal.com Tokens',
            },
        ),
    ]
