# Generated by Django 5.2.4 on 2026-01-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenerprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Languages the listener can speak'),
        ),
    ]
