# Generated by Django 5.2.4 on 2026-01-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0002_listenerprofile_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenerprofile',
            name='accept_direct_calls',
            field=models.BooleanField(default=True, help_text='Accept direct calls from talkers'),
        ),
        migrations.AlterField(
            model_name='listenerprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Available for sessions'),
        ),
    ]
