# Generated by Django 5.2.4 on 2026-01-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0003_listenerprofile_accept_direct_calls_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListenerAvailability',
        ),
    ]
