# Generated by Django 5.2.4 on 2026-01-13 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0004_delete_listeneravailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')])),
                ('review', models.TextField(blank=True, help_text='Optional review comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='listener.listenerprofile')),
                ('talker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listener_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listener Rating',
                'verbose_name_plural': 'Listener Ratings',
                'unique_together': {('listener', 'talker')},
            },
        ),
    ]
