# Generated by Django 5.2.4 on 2026-01-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0005_listenerrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenerprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text='List of listening specialties'),
        ),
    ]
