# Generated by Django 5.2.4 on 2026-01-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0005_listenerrating'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE listener_listenerprofile
                SET specialties = CASE
                    WHEN specialties IS NULL OR btrim(specialties) = '' OR lower(btrim(specialties)) IN ('undefined', 'null', 'none')
                        THEN '[]'
                    WHEN left(ltrim(specialties), 1) IN ('[', '{')
                        THEN specialties
                    ELSE to_json(regexp_split_to_array(specialties, '\\s*,\\s*'))::text
                END;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='listenerprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text='List of listening specialties'),
        ),
    ]
