# Generated by Django 5.2.4 on 2026-01-25 04:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0006_alter_listenerprofile_specialties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current available balance', max_digits=10)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total money earned (lifetime)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listener', models.OneToOneField(limit_choices_to={'user_type': 'listener'}, on_delete=django.db.models.deletion.CASCADE, related_name='balance_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listener Balance',
                'verbose_name_plural': 'Listener Balances',
            },
        ),
    ]
