# Generated by Django 5.2.4 on 2026-02-01 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0007_listenerbalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerBlockedTalker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_talkers', to=settings.AUTH_USER_MODEL)),
                ('talker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_listeners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listener Blocked Talker',
                'verbose_name_plural': 'Listener Blocked Talkers',
                'ordering': ['-blocked_at'],
                'unique_together': {('listener', 'talker')},
            },
        ),
    ]
