# Generated by Django 5.2.4 on 2026-06-25 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0009_listenerbookingrefund'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listenerbookingrefund',
            new_name='listener_li_listene_f1a64d_idx',
            old_name='listener_li_listene_4222e8_idx',
        ),
    ]
