# Generated by Django 5.2.4 on 2026-01-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='otp',
            name='user_type',
            field=models.CharField(blank=True, default='talker', max_length=20),
        ),
    ]
