# Generated by Django 5.2.4 on 2026-02-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='otp',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='otp',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user_type',
            field=models.CharField(choices=[('talker', 'Talker'), ('listener', 'Listener')], default='talker', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
