# Generated by Django 5.2.4 on 2026-03-17 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_remove_otp_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_access_token', models.TextField()),
                ('cal_refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('cal_user_id', models.CharField(blank=True, help_text='Cal.com user ID or email', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cal_mapping', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cal.com User Mapping',
                'verbose_name_plural': 'Cal.com User Mappings',
            },
        ),
    ]
