# Generated by Django 5.2.4 on 2026-06-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_otp_country'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passwordresetotp',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='otp',
            name='country',
            field=models.CharField(blank=True, help_text='User selected country during registration', max_length=100),
        ),
    ]
