# Generated by Django 5.2.4 on 2026-02-21 06:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_callsession_agora_channel_name_and_more'),
        ('payment', '0002_alter_payment_stripe_payment_intent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_portion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listener_portion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('listener_percentage', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=5)),
                ('transaction_type', models.CharField(choices=[('call', 'Call Payment'), ('extension', 'Call Extension')], default='call', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_tracking', to='chat.callpackage')),
                ('listener', models.ForeignKey(limit_choices_to={'user_type': 'listener'}, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_earnings', to=settings.AUTH_USER_MODEL)),
                ('talker', models.ForeignKey(limit_choices_to={'user_type': 'talker'}, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revenue Tracking',
                'verbose_name_plural': 'Revenue Tracking',
                'ordering': ['-created_at'],
            },
        ),
    ]
