# Generated by Django 5.2.4 on 2026-03-05 04:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_revenuetracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Tip amount in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('admin_fee', models.DecimalField(decimal_places=2, help_text='Admin commission (10%)', max_digits=10)),
                ('listener_amount', models.DecimalField(decimal_places=2, help_text='Amount credited to listener (90%)', max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True, help_text='Optional message with the tip')),
                ('failure_reason', models.TextField(blank=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('listener', models.ForeignKey(limit_choices_to={'user_type': 'listener'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_tips', to=settings.AUTH_USER_MODEL)),
                ('talker', models.ForeignKey(limit_choices_to={'user_type': 'talker'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tip',
                'verbose_name_plural': 'Tips',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['talker', '-created_at'], name='payment_tip_talker__94918d_idx'), models.Index(fields=['listener', '-created_at'], name='payment_tip_listene_7a58ca_idx'), models.Index(fields=['status', '-created_at'], name='payment_tip_status_0b8a60_idx'), models.Index(fields=['stripe_payment_intent_id'], name='payment_tip_stripe__6d3ddd_idx')],
            },
        ),
    ]
