# Generated by Django 5.2.4 on 2026-05-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, default='', help_text='Stripe transfer ID to listener account', max_length=255),
        ),
    ]
