# Generated by Django 5.2.4 on 2026-04-03 05:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalBookingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Package name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Package description')),
                ('package_type', models.CharField(choices=[('one_time', 'One-Time'), ('recurring', 'Recurring')], default='one_time', help_text='Type of booking package', max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Session duration', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='minutes', help_text='Unit for session duration', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('app_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='App commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Package available for booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Universal Booking Package',
                'verbose_name_plural': 'Universal Booking Packages',
                'ordering': ['duration', 'price'],
            },
        ),
    ]
