# Generated by Django 5.2.4 on 2026-04-05 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokking', '0002_universalbookingpackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universalbookingpackage',
            name='duration_unit',
        ),
        migrations.AlterField(
            model_name='universalbookingpackage',
            name='duration',
            field=models.PositiveIntegerField(help_text='Session duration in minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
