# Generated by Django 5.2.4 on 2026-04-05 03:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokking', '0003_remove_universalbookingpackage_duration_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateField(help_text='Date of the booking')),
                ('start_time', models.TimeField(help_text='Start time of the session')),
                ('end_time', models.TimeField(help_text='End time of the session')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('buffer_time_minutes', models.PositiveIntegerField(default=5, help_text='Buffer time after booking before next slot')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current booking status', max_length=20)),
                ('payment_link', models.URLField(blank=True, help_text='Payment link for the booking', null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment transaction ID', max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price charged for booking', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('app_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='App commission fee', max_digits=10)),
                ('listener_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid to listener', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('listener', models.ForeignKey(help_text='Listener providing the session', on_delete=django.db.models.deletion.CASCADE, related_name='session_bookings_as_listener', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(help_text='Booking package selected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_bookings', to='bokking.universalbookingpackage')),
                ('talker', models.ForeignKey(help_text='Talker who is booking the session', on_delete=django.db.models.deletion.CASCADE, related_name='session_bookings_as_talker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Booking',
                'verbose_name_plural': 'Session Bookings',
                'ordering': ['-booking_date', 'start_time'],
                'indexes': [models.Index(fields=['listener', 'booking_date'], name='bokking_ses_listene_dde26e_idx'), models.Index(fields=['talker', 'status'], name='bokking_ses_talker__ade721_idx'), models.Index(fields=['status', 'booking_date'], name='bokking_ses_status_f40e33_idx')],
            },
        ),
    ]
