# Generated by Django 5.2.4 on 2026-04-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokking', '0007_universalbookingpackage_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount refunded to payment card', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='When refund was processed to payment card', null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='stripe_refund_id',
            field=models.CharField(blank=True, help_text='Stripe refund ID when booking is cancelled', max_length=255, null=True),
        ),
    ]
