# Generated by Django 5.2.4 on 2026-04-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokking', '0008_sessionbooking_refund_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbooking',
            name='payment_link',
            field=models.URLField(blank=True, help_text='Payment link for the booking', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Payment transaction ID', max_length=255, null=True),
        ),
    ]
